[tool.poetry]
name = "catalax"
version = "0.2.0"
description = "A JAX-based framework for (neural) ODE modelling in biocatalysis."
authors = ["Jan Range <30547301+JR-1991@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
matplotlib = "^3.8.0"
pydantic = "1.10.7"
dotted-dict = "^1.1.3"
sympy = "^1.12"
diffrax = "^0.4.1"
pandas = "^2.1.1"
tqdm = "^4.66.1"
numpy = "^1.26.0"
numpyro = "^0.13.2"
arviz = "^0.16.1"
corner = "^2.2.2"
optax = "^0.1.7"
equinox = "^0.11.0"
lmfit = "^1.2.2"

[tool.poetry.extras]
identifiability = ["julia", "jinja2"]

[tool.setuptools.packages.find]
where = ["catalax"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
